language: c
sudo: true

matrix:
  include:
#
    - os: linux
      compiler: clang
      addons:
        apt:
          source:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
          packages:
           - clang-3.8
#
    - os: linux
      compiler: gcc
      addons:
          apt:
            packages:
              - gcc-4.8

# Install dependencies
addons:
  apt:
    packages:
      - make

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libzip-dev liblz4-dev libssl-dev libbz2-dev

# Build library.
script:
  - make -C .
  - sudo make -C . install
  - mkdir build && cd build

